export const translations = {
  en: {
    languageName: "English",
    controls: { language: "Choose language", light: "Switch to light mode", dark: "Switch to dark mode" },
    nav: { aria: "Primary navigation", top: "Tri Do, back to top", work: "Work", experience: "Experience", skills: "Skills", about: "About", resume: "Résumé" },
    hero: {
      eyebrow: "Junior Full-Stack Developer · Moncton, NB",
      title: "I build reliable products from interface to database.",
      lede: "Recent NBCC Software Development graduate with hands-on experience building React and Next.js interfaces, mobile apps, typed APIs, authentication, and database-backed workflows.",
      view: "View ShopPilot", download: "Download résumé",
      locationAria: "Availability and location", location: "Based in Moncton, Canada", availability: "Open to junior roles across Canada",
    },
    proof: {
      aria: "Featured engineering snapshot", shipping: "Currently shipping", active: "Active project", flagship: "Flagship project",
      description: "Merchant operations across products, inventory, orders, storage, and analytics.",
      commits: "Git commits", platforms: "Platforms", isolation: "Data isolation", caseStudy: "Read the engineering case study",
    },
    highlights: { aria: "Portfolio highlights", internship: "Professional internship", projects: "Selected projects", experience: "End-to-end product experience" },
    work: {
      kicker: "Selected work", title: "Evidence over buzzwords.",
      intro: "A focused set of projects showing product thinking, implementation depth, and the ability to finish practical software.",
      featured: "Flagship project", type: "Cross-platform merchant operations",
      summary: "A production-style merchant dashboard for managing products, inventory, orders, store settings, images, and performance analytics from one responsive app.",
      live: "Open live app", source: "View source",
      engineering: [
        "Supabase authentication, protected routes, and session recovery",
        "PostgreSQL Row Level Security for merchant-owned data and files",
        "Product CRUD, inventory filters, image upload, orders, and refunds",
        "Typed data access with revenue, conversion, and product analytics",
      ],
      screenshotsAria: "ShopPilot screenshots", viewGithub: "View {title} on GitHub",
    },
    shots: [
      { label: "Dashboard", alt: "ShopPilot merchant dashboard showing revenue, orders, inventory, and conversion metrics" },
      { label: "Products", alt: "ShopPilot product management screen with search, filters, pricing, and inventory" },
      { label: "Insights", alt: "ShopPilot analytics screen showing weekly revenue and inventory risks" },
    ],
    projects: [
      { type: "Full-stack web application", title: "Restaurant Event Management", description: "A database-backed event system with server-rendered views, validated forms, search by name and date, and archive-based deletion.", signals: ["MVC architecture", "Server-side validation", "Search and archive workflows"] },
      { type: "Backend REST API", title: "License Plate Assignment API", description: "A REST API that validates VINs and manages Ontario-style plate assignment, verification, and revocation with persistent storage.", signals: ["API-key middleware", "Validation and error handling", "Documented request workflows"] },
      { type: "Front-end engineering", title: "Developer Portfolio", description: "This responsive portfolio turns project work into scannable evidence with accessible interactions, focused content, and performance-conscious media.", signals: ["Responsive layout", "Semantic structure", "Optimized project media"] },
    ],
    career: {
      kicker: "Experience & education", title: "Built on real delivery.", experience: "Experience", education: "Education",
      internTitle: "Backend Developer Intern", internPoints: [
        "Developed and supported server-side application logic and CRUD workflows for web applications.",
        "Worked with API, database, validation, debugging, and feature-testing workflows.",
        "Collaborated with a supervisor and development team to complete assigned features reliably.",
      ],
      diploma: "Information Technology: Software Development",
      college: "New Brunswick Community College · Moncton",
      educationText: "Diploma program covering full-stack web development, databases, APIs, mobile development, testing, and collaborative software delivery.",
    },
    skills: {
      kicker: "Capabilities", title: "Tools connected to outcomes.",
      intro: "The stack is broad, but the focus is consistent: clear interfaces, dependable application logic, and maintainable data flows.",
      groups: [
        { title: "Front end", description: "Interfaces that stay clear across desktop and mobile." },
        { title: "Back end", description: "APIs and application logic built around real workflows." },
        { title: "Data & platform", description: "Practical data models, access controls, and integrations." },
        { title: "Mobile & workflow", description: "Cross-platform delivery with a disciplined toolchain." },
      ],
    },
    about: {
      kicker: "About", title: "I like the complete build process.",
      first: "I’m Tri, a recent Software Development graduate who enjoys moving from an unclear problem to a working product: shaping the interface, defining the data, building the workflow, and testing the result.",
      second: "I’m looking for a junior team where I can contribute to real products, learn from experienced developers, and keep growing into a dependable software engineer.",
      contactKicker: "Let’s work together", contactTitle: "Open to junior opportunities across Canada.",
      contactText: "Front-end, full-stack, and software development roles are the best fit.", email: "Email me", github: "GitHub profile", linkedin: "LinkedIn profile",
    },
    footer: { built: "Built with Next.js, TypeScript, and intention.", top: "Back to top" },
  },
  fr: {
    languageName: "Français",
    controls: { language: "Choisir la langue", light: "Passer au mode clair", dark: "Passer au mode sombre" },
    nav: { aria: "Navigation principale", top: "Tri Do, retour en haut", work: "Projets", experience: "Expérience", skills: "Compétences", about: "À propos", resume: "CV" },
    hero: {
      eyebrow: "Développeur full-stack junior · Moncton, N.-B.",
      title: "Je crée des produits fiables, de l’interface à la base de données.",
      lede: "Récemment diplômé en développement de logiciels au NBCC, avec une expérience pratique des interfaces React et Next.js, des applications mobiles, des API typées, de l’authentification et des flux soutenus par une base de données.",
      view: "Voir ShopPilot", download: "Télécharger le CV",
      locationAria: "Disponibilité et emplacement", location: "Basé à Moncton, Canada", availability: "Ouvert aux postes juniors partout au Canada",
    },
    proof: {
      aria: "Aperçu technique du projet vedette", shipping: "En développement actif", active: "Projet actif", flagship: "Projet principal",
      description: "Gestion des produits, des stocks, des commandes, du stockage et des analyses pour les commerçants.",
      commits: "Commits Git", platforms: "Plateformes", isolation: "Isolation des données", caseStudy: "Voir l’étude de cas technique",
    },
    highlights: { aria: "Points forts du portfolio", internship: "Stage professionnel", projects: "Projets sélectionnés", experience: "Expérience produit de bout en bout" },
    work: {
      kicker: "Projets sélectionnés", title: "Des preuves, pas des mots à la mode.",
      intro: "Une sélection ciblée de projets qui démontre la réflexion produit, la profondeur technique et la capacité à livrer des logiciels utiles.",
      featured: "Projet principal", type: "Opérations commerciales multiplateformes",
      summary: "Un tableau de bord de niveau production pour gérer les produits, les stocks, les commandes, les paramètres, les images et les analyses dans une application responsive.",
      live: "Ouvrir l’application", source: "Voir le code source",
      engineering: [
        "Authentification Supabase, routes protégées et récupération de session",
        "Sécurité PostgreSQL au niveau des lignes pour les données et fichiers des commerçants",
        "CRUD des produits, filtres de stock, téléversement d’images, commandes et remboursements",
        "Accès typé aux données pour les revenus, la conversion et les analyses produits",
      ],
      screenshotsAria: "Captures d’écran de ShopPilot", viewGithub: "Voir {title} sur GitHub",
    },
    shots: [
      { label: "Tableau de bord", alt: "Tableau de bord ShopPilot affichant les revenus, commandes, stocks et conversions" },
      { label: "Produits", alt: "Écran ShopPilot de gestion des produits avec recherche, filtres, prix et stocks" },
      { label: "Analyses", alt: "Écran d’analyses ShopPilot avec revenus hebdomadaires et risques de stock" },
    ],
    projects: [
      { type: "Application web full-stack", title: "Restaurant Event Management", description: "Un système d’événements connecté à une base de données, avec vues rendues côté serveur, formulaires validés, recherche et archivage.", signals: ["Architecture MVC", "Validation côté serveur", "Recherche et archivage"] },
      { type: "API REST backend", title: "License Plate Assignment API", description: "Une API REST qui valide les NIV et gère l’attribution, la vérification et la révocation de plaques ontariennes avec stockage persistant.", signals: ["Middleware par clé API", "Validation et gestion des erreurs", "Flux de requêtes documentés"] },
      { type: "Ingénierie front-end", title: "Developer Portfolio", description: "Ce portfolio responsive transforme les projets en preuves faciles à parcourir grâce à des interactions accessibles, un contenu ciblé et des médias optimisés.", signals: ["Mise en page responsive", "Structure sémantique", "Médias de projet optimisés"] },
    ],
    career: {
      kicker: "Expérience et formation", title: "Fondé sur des réalisations concrètes.", experience: "Expérience", education: "Formation",
      internTitle: "Stagiaire développeur backend", internPoints: [
        "Développement et soutien de la logique serveur et de flux CRUD pour des applications web.",
        "Travail avec les API, les bases de données, la validation, le débogage et les tests de fonctionnalités.",
        "Collaboration avec un superviseur et une équipe de développement pour livrer les fonctionnalités assignées.",
      ],
      diploma: "Technologies de l’information : développement de logiciels",
      college: "Collège communautaire du Nouveau-Brunswick · Moncton",
      educationText: "Programme couvrant le développement web full-stack, les bases de données, les API, le développement mobile, les tests et la livraison collaborative de logiciels.",
    },
    skills: {
      kicker: "Compétences", title: "Des outils reliés aux résultats.",
      intro: "La pile est variée, mais l’objectif demeure le même : des interfaces claires, une logique fiable et des flux de données faciles à maintenir.",
      groups: [
        { title: "Front-end", description: "Des interfaces claires sur ordinateur comme sur mobile." },
        { title: "Backend", description: "Des API et une logique applicative adaptées à de vrais flux de travail." },
        { title: "Données et plateforme", description: "Des modèles de données, contrôles d’accès et intégrations pratiques." },
        { title: "Mobile et outils", description: "Une livraison multiplateforme appuyée par une chaîne d’outils rigoureuse." },
      ],
    },
    about: {
      kicker: "À propos", title: "J’aime participer à tout le processus de création.",
      first: "Je m’appelle Tri. Récemment diplômé en développement de logiciels, j’aime transformer un problème flou en produit fonctionnel : concevoir l’interface, définir les données, bâtir le flux et tester le résultat.",
      second: "Je recherche une équipe où je pourrai contribuer à de vrais produits, apprendre auprès de développeurs expérimentés et devenir un ingénieur logiciel fiable.",
      contactKicker: "Travaillons ensemble", contactTitle: "Ouvert aux occasions juniors partout au Canada.",
      contactText: "Les postes en front-end, full-stack et développement logiciel me correspondent le mieux.", email: "M’écrire", github: "Profil GitHub", linkedin: "Profil LinkedIn",
    },
    footer: { built: "Créé avec Next.js, TypeScript et beaucoup d’attention.", top: "Retour en haut" },
  },
  vi: {
    languageName: "Tiếng Việt",
    controls: { language: "Chọn ngôn ngữ", light: "Chuyển sang giao diện sáng", dark: "Chuyển sang giao diện tối" },
    nav: { aria: "Điều hướng chính", top: "Tri Do, về đầu trang", work: "Dự án", experience: "Kinh nghiệm", skills: "Kỹ năng", about: "Giới thiệu", resume: "CV" },
    hero: {
      eyebrow: "Lập trình viên Full-Stack Junior · Moncton, NB",
      title: "Tôi xây dựng sản phẩm đáng tin cậy từ giao diện đến cơ sở dữ liệu.",
      lede: "Tân cử nhân ngành Phát triển Phần mềm tại NBCC, có kinh nghiệm thực tế với giao diện React và Next.js, ứng dụng di động, API có kiểu dữ liệu, xác thực và quy trình kết nối cơ sở dữ liệu.",
      view: "Xem ShopPilot", download: "Tải CV",
      locationAria: "Địa điểm và khả năng làm việc", location: "Đang sống tại Moncton, Canada", availability: "Sẵn sàng cho vị trí junior trên toàn Canada",
    },
    proof: {
      aria: "Tóm tắt kỹ thuật dự án nổi bật", shipping: "Đang phát triển", active: "Dự án đang hoạt động", flagship: "Dự án chủ lực",
      description: "Quản lý sản phẩm, tồn kho, đơn hàng, lưu trữ và phân tích dành cho cửa hàng.",
      commits: "Git commits", platforms: "Nền tảng", isolation: "Tách biệt dữ liệu", caseStudy: "Xem nghiên cứu kỹ thuật",
    },
    highlights: { aria: "Điểm nổi bật của portfolio", internship: "Kỳ thực tập chuyên môn", projects: "Dự án được chọn", experience: "Kinh nghiệm sản phẩm đầu-cuối" },
    work: {
      kicker: "Dự án tiêu biểu", title: "Minh chứng quan trọng hơn từ khóa.",
      intro: "Những dự án chọn lọc thể hiện tư duy sản phẩm, chiều sâu triển khai và khả năng hoàn thiện phần mềm thực tế.",
      featured: "Dự án chủ lực", type: "Vận hành cửa hàng đa nền tảng",
      summary: "Bảng điều khiển theo hướng sản phẩm thực tế, giúp quản lý sản phẩm, tồn kho, đơn hàng, cài đặt cửa hàng, hình ảnh và số liệu hiệu suất trong một ứng dụng responsive.",
      live: "Mở ứng dụng", source: "Xem mã nguồn",
      engineering: [
        "Xác thực Supabase, route được bảo vệ và khôi phục phiên đăng nhập",
        "PostgreSQL Row Level Security bảo vệ dữ liệu và tệp của từng cửa hàng",
        "CRUD sản phẩm, lọc tồn kho, tải ảnh, xử lý đơn hàng và hoàn tiền",
        "Truy cập dữ liệu có kiểu cho doanh thu, tỷ lệ chuyển đổi và phân tích sản phẩm",
      ],
      screenshotsAria: "Ảnh giao diện ShopPilot", viewGithub: "Xem {title} trên GitHub",
    },
    shots: [
      { label: "Tổng quan", alt: "Bảng điều khiển ShopPilot hiển thị doanh thu, đơn hàng, tồn kho và tỷ lệ chuyển đổi" },
      { label: "Sản phẩm", alt: "Màn hình quản lý sản phẩm ShopPilot với tìm kiếm, bộ lọc, giá và tồn kho" },
      { label: "Phân tích", alt: "Màn hình phân tích ShopPilot hiển thị doanh thu tuần và rủi ro tồn kho" },
    ],
    projects: [
      { type: "Ứng dụng web full-stack", title: "Restaurant Event Management", description: "Hệ thống sự kiện kết nối cơ sở dữ liệu với giao diện render từ server, biểu mẫu có xác thực, tìm kiếm theo tên/ngày và cơ chế lưu trữ thay vì xóa hẳn.", signals: ["Kiến trúc MVC", "Xác thực phía server", "Quy trình tìm kiếm và lưu trữ"] },
      { type: "Backend REST API", title: "License Plate Assignment API", description: "REST API xác thực VIN và quản lý việc cấp, kiểm tra, thu hồi biển số theo định dạng Ontario với dữ liệu được lưu bền vững.", signals: ["Middleware API key", "Xác thực và xử lý lỗi", "Quy trình request có tài liệu"] },
      { type: "Kỹ thuật front-end", title: "Developer Portfolio", description: "Portfolio responsive này biến các dự án thành bằng chứng dễ đọc với tương tác dễ tiếp cận, nội dung tập trung và hình ảnh được tối ưu.", signals: ["Bố cục responsive", "Cấu trúc semantic", "Hình ảnh dự án được tối ưu"] },
    ],
    career: {
      kicker: "Kinh nghiệm và học vấn", title: "Xây dựng từ trải nghiệm thực tế.", experience: "Kinh nghiệm", education: "Học vấn",
      internTitle: "Thực tập sinh Backend Developer", internPoints: [
        "Phát triển và hỗ trợ logic phía server cùng các quy trình CRUD cho ứng dụng web.",
        "Làm việc với API, cơ sở dữ liệu, xác thực, gỡ lỗi và kiểm thử tính năng.",
        "Phối hợp với người hướng dẫn và nhóm phát triển để hoàn thành các tính năng được giao.",
      ],
      diploma: "Công nghệ Thông tin: Phát triển Phần mềm",
      college: "New Brunswick Community College · Moncton",
      educationText: "Chương trình đào tạo phát triển web full-stack, cơ sở dữ liệu, API, ứng dụng di động, kiểm thử và quy trình phát triển phần mềm theo nhóm.",
    },
    skills: {
      kicker: "Năng lực", title: "Công nghệ gắn liền với kết quả.",
      intro: "Công nghệ có thể đa dạng, nhưng trọng tâm luôn nhất quán: giao diện rõ ràng, logic ứng dụng đáng tin cậy và luồng dữ liệu dễ bảo trì.",
      groups: [
        { title: "Front end", description: "Giao diện rõ ràng trên cả máy tính và thiết bị di động." },
        { title: "Back end", description: "API và logic ứng dụng phục vụ những quy trình thực tế." },
        { title: "Dữ liệu và nền tảng", description: "Mô hình dữ liệu, kiểm soát truy cập và tích hợp thiết thực." },
        { title: "Di động và quy trình", description: "Phát triển đa nền tảng với bộ công cụ có tổ chức." },
      ],
    },
    about: {
      kicker: "Giới thiệu", title: "Tôi thích toàn bộ quá trình xây dựng sản phẩm.",
      first: "Tôi là Tri, một tân cử nhân Phát triển Phần mềm. Tôi thích biến một vấn đề chưa rõ ràng thành sản phẩm hoạt động được: thiết kế giao diện, xác định dữ liệu, xây dựng quy trình và kiểm thử kết quả.",
      second: "Tôi đang tìm một đội ngũ phù hợp với junior, nơi tôi có thể đóng góp vào sản phẩm thực tế, học hỏi từ các lập trình viên giàu kinh nghiệm và phát triển thành một kỹ sư phần mềm đáng tin cậy.",
      contactKicker: "Cùng làm việc nhé", contactTitle: "Sẵn sàng cho cơ hội junior trên toàn Canada.",
      contactText: "Các vị trí front-end, full-stack và phát triển phần mềm là phù hợp nhất.", email: "Gửi email", github: "Trang GitHub", linkedin: "Trang LinkedIn",
    },
    footer: { built: "Xây dựng bằng Next.js, TypeScript và sự chỉn chu.", top: "Về đầu trang" },
  },
} as const;

export type Language = keyof typeof translations;

