export const translations = {
  en: {
    languageName: "English",
    controls: { language: "Choose language", light: "Switch to light mode", dark: "Switch to dark mode" },
    nav: { aria: "Primary navigation", top: "Tri Do, back to top", work: "Work", experience: "Experience", skills: "Skills", about: "About", resume: "Résumé" },
    hero: {
      eyebrow: "Junior Full-Stack Developer | React · Next.js · TypeScript",
      title: "I build reliable products from interface to database.",
      lede: "Recent NBCC Software Development graduate with hands-on experience building React and Next.js interfaces, mobile apps, typed APIs, authentication, and database-backed workflows.",
      view: "View ShopPilot", download: "Full-stack résumé", frontEndResume: "Front-end résumé",
      locationAria: "Availability and location", location: "Based in Moncton, Canada", availability: "Open to junior roles across Canada",
    },
    proof: {
      aria: "Featured engineering snapshot", shipping: "Currently shipping", active: "Active project", flagship: "Flagship project",
      description: "Merchant operations across products, inventory, orders, storage, and analytics.",
      commits: "Git commits", platforms: "Platforms", isolation: "Data isolation", caseStudy: "Explore the architecture",
    },
    highlights: { aria: "Portfolio highlights", internship: "Professional internship", projects: "Selected projects", experience: "End-to-end product experience" },
    work: {
      kicker: "Selected work", title: "Evidence over buzzwords.",
      intro: "A focused set of projects showing product thinking, implementation depth, and the ability to finish practical software.",
      featured: "Flagship project", type: "Cross-platform merchant operations",
      summary: "A production-style merchant dashboard for managing products, inventory, orders, store settings, images, and performance analytics from one responsive app.",
      live: "Open app (sign in)", source: "View source", preview: "Preview screens",
      previewTitle: "ShopPilot screenshot tour",
      previewIntro: "Explore the merchant app screens below. No account needed.",
      loginNote: "The live app requires a merchant account.",
      engineering: [
        "Supabase authentication, protected routes, and session recovery",
        "PostgreSQL Row Level Security for merchant-owned data and files",
        "Product CRUD, inventory filters, image upload, orders, and refunds",
        "Typed data access with revenue, conversion, and product analytics",
      ],
      screenshotsAria: "ShopPilot screenshots", viewGithub: "Open {title}",
    },
    shots: [
      { label: "Dashboard", alt: "ShopPilot merchant dashboard showing revenue, orders, inventory, and conversion metrics", caption: "The dashboard brings revenue, open orders, inventory alerts, and recent activity into one view." },
      { label: "Products", alt: "ShopPilot product management screen with search, filters, pricing, and inventory", caption: "The product screen groups search, stock filters, pricing, and publishing status for everyday inventory work." },
      { label: "Insights", alt: "ShopPilot analytics screen showing weekly revenue and inventory risks", caption: "Insights shows sample analytics for revenue, storefront activity, conversion, and inventory risks." },
    ],
    projects: [
      {"type": "Next.js storefront", "title": "ShopPilot Storefront", "description": "The customer-facing side of ShopPilot: published store pages, product browsing, and a local cart connected to the merchant app’s Supabase data. Checkout and payments are outside the current MVP.", "signals": ["Reusable React components", "Product and cart flows", "Storefront analytics events"]},
      { type: "Full-stack booking platform", title: "ScheduleBooker", description: "A multilingual Flask appointment platform with guest and customer booking, conflict-safe availability, admin calendars and reporting, audited cancellation, and production PostgreSQL persistence.", signals: ["Responsive booking flows", "PostgreSQL + migrations", "Security and automated tests"] },
      { type: "Full-stack web application", title: "Restaurant Event Management", description: "A database-backed event system with server-rendered views, validated forms, search by name and date, and archive-based deletion.", signals: ["MVC architecture", "Server-side validation", "Search and archive workflows"] },
      { type: "Backend REST API", title: "License Plate Assignment API", description: "A REST API that validates VINs and manages Ontario-style plate assignment, verification, and revocation with persistent storage.", signals: ["API-key middleware", "Validation and error handling", "Documented request workflows"] },
    ],
    career: {
      kicker: "Experience & education", title: "Built on real delivery.", experience: "Experience", education: "Education",
      internTitle: "Software Development Intern", internPoints: [
        "Implemented a rating feature, tested its behavior, and resolved issues using supervisor feedback.",
        "Developed and tested CRUD workflows, input validation, and database-connected application logic.",
        "Used Git to manage changes within a development team and documented progress for the supervisor.",
      ],
      diploma: "Information Technology: Software Development",
      college: "New Brunswick Community College · Moncton",
      educationText: "Diploma program covering full-stack web development, databases, APIs, mobile development, testing, and collaborative software delivery.",
    },
    skills: {
      kicker: "Capabilities", title: "Tools connected to outcomes.",
      intro: "The stack is broad, but the focus is consistent: clear interfaces, dependable application logic, and maintainable data flows.",
      groups: [
        { title: "Front end", description: "Interfaces that stay clear across desktop and mobile." },
        { title: "Back end", description: "APIs and application logic built around real workflows." },
        { title: "Data & platform", description: "Practical data models, access controls, and integrations." },
        { title: "Mobile & workflow", description: "Cross-platform delivery with a disciplined toolchain." },
      ],
    },
    about: {
      kicker: "About", title: "I like the complete build process.",
      first: "I’m Tri, a recent Software Development graduate who enjoys moving from an unclear problem to a working product: shaping the interface, defining the data, building the workflow, and testing the result.",
      second: "I’m looking for a junior team where I can contribute to real products, learn from experienced developers, and keep growing into a dependable software engineer.",
      contactKicker: "Let’s work together", contactTitle: "Open to junior opportunities across Canada.",
      contactText: "Front-end, full-stack, and software development roles are the best fit.", email: "Email me", github: "GitHub profile", linkedin: "LinkedIn profile",
    },
    footer: { built: "Built with Next.js, TypeScript, and intention.", top: "Back to top" },
  },
  fr: {
    languageName: "Français",
    controls: { language: "Choisir la langue", light: "Passer au mode clair", dark: "Passer au mode sombre" },
    nav: { aria: "Navigation principale", top: "Tri Do, retour en haut", work: "Projets", experience: "Expérience", skills: "Compétences", about: "À propos", resume: "CV" },
    hero: {
      eyebrow: "Junior Full-Stack Developer | React · Next.js · TypeScript",
      title: "Je crée des produits fiables, de l’interface à la base de données.",
      lede: "Récemment diplômé en développement de logiciels au NBCC, avec une expérience pratique des interfaces React et Next.js, des applications mobiles, des API typées, de l’authentification et des flux soutenus par une base de données.",
      view: "Voir ShopPilot", download: "CV Full-stack", frontEndResume: "CV Front-end",
      locationAria: "Disponibilité et emplacement", location: "Basé à Moncton, Canada", availability: "Ouvert aux postes juniors partout au Canada",
    },
    proof: {
      aria: "Aperçu technique du projet vedette", shipping: "En développement actif", active: "Projet actif", flagship: "Projet principal",
      description: "Gestion des produits, des stocks, des commandes, du stockage et des analyses pour les commerçants.",
      commits: "Commits Git", platforms: "Plateformes", isolation: "Isolation des données", caseStudy: "Explorer l’architecture",
    },
    highlights: { aria: "Points forts du portfolio", internship: "Stage professionnel", projects: "Projets sélectionnés", experience: "Expérience produit de bout en bout" },
    work: {
      kicker: "Projets sélectionnés", title: "Des preuves, pas des mots à la mode.",
      intro: "Une sélection ciblée de projets qui démontre la réflexion produit, la profondeur technique et la capacité à livrer des logiciels utiles.",
      featured: "Projet principal", type: "Opérations commerciales multiplateformes",
      summary: "Un tableau de bord de niveau production pour gérer les produits, les stocks, les commandes, les paramètres, les images et les analyses dans une application responsive.",
      live: "Ouvrir l’app (connexion)", source: "Voir le code source", preview: "Voir les écrans",
      previewTitle: "Aperçu des écrans ShopPilot",
      previewIntro: "Découvrez les écrans de l’application commerçant ci-dessous. Aucun compte requis.",
      loginNote: "L’application en ligne nécessite un compte commerçant.",
      engineering: [
        "Authentification Supabase, routes protégées et récupération de session",
        "Sécurité PostgreSQL au niveau des lignes pour les données et fichiers des commerçants",
        "CRUD des produits, filtres de stock, téléversement d’images, commandes et remboursements",
        "Accès typé aux données pour les revenus, la conversion et les analyses produits",
      ],
      screenshotsAria: "Captures d’écran de ShopPilot", viewGithub: "Ouvrir {title}",
    },
    shots: [
      { label: "Tableau de bord", alt: "Tableau de bord ShopPilot affichant les revenus, commandes, stocks et conversions", caption: "Le tableau de bord réunit les revenus, les commandes ouvertes, les alertes de stock et l’activité récente." },
      { label: "Produits", alt: "Écran ShopPilot de gestion des produits avec recherche, filtres, prix et stocks", caption: "La recherche, les filtres de stock, les prix et l’état de publication facilitent la gestion quotidienne des produits." },
      { label: "Analyses", alt: "Écran d’analyses ShopPilot avec revenus hebdomadaires et risques de stock", caption: "Les analyses présentent des données de démonstration sur les revenus, les visites, la conversion et les risques de stock." },
    ],
    projects: [
      {"type": "Vitrine Next.js", "title": "ShopPilot Storefront", "description": "La vitrine client de ShopPilot propose des pages de boutique, un catalogue et un panier local reliés aux données Supabase de l’application commerçant. La commande et le paiement ne font pas partie du MVP actuel.", "signals": ["Composants React réutilisables", "Catalogue et panier", "Événements analytiques"]},
      { type: "Plateforme de réservation full-stack", title: "ScheduleBooker", description: "Une plateforme de rendez-vous Flask multilingue avec réservation client et invité, disponibilité sans conflit, calendriers et rapports administratifs, annulation auditée et PostgreSQL en production.", signals: ["Flux de réservation responsive", "PostgreSQL + migrations", "Sécurité et tests automatisés"] },
      { type: "Application web full-stack", title: "Restaurant Event Management", description: "Un système d’événements connecté à une base de données, avec vues rendues côté serveur, formulaires validés, recherche et archivage.", signals: ["Architecture MVC", "Validation côté serveur", "Recherche et archivage"] },
      { type: "API REST backend", title: "License Plate Assignment API", description: "Une API REST qui valide les NIV et gère l’attribution, la vérification et la révocation de plaques ontariennes avec stockage persistant.", signals: ["Middleware par clé API", "Validation et gestion des erreurs", "Flux de requêtes documentés"] },
    ],
    career: {
      kicker: "Expérience et formation", title: "Fondé sur des réalisations concrètes.", experience: "Expérience", education: "Formation",
      internTitle: "Stagiaire en développement logiciel", internPoints: [
        "Développement d’une fonctionnalité de notation, vérification de son comportement et correction de problèmes avec les retours du superviseur.",
        "Développement et tests de flux CRUD, de validation des entrées et de logique applicative reliée à la base de données.",
        "Utilisation de Git au sein d’une équipe de développement et documentation des progrès pour le superviseur.",
      ],
      diploma: "Technologies de l’information : développement de logiciels",
      college: "New Brunswick Community College (NBCC) · Moncton",
      educationText: "Programme couvrant le développement web full-stack, les bases de données, les API, le développement mobile, les tests et la livraison collaborative de logiciels.",
    },
    skills: {
      kicker: "Compétences", title: "Des outils reliés aux résultats.",
      intro: "La pile est variée, mais l’objectif demeure le même : des interfaces claires, une logique fiable et des flux de données faciles à maintenir.",
      groups: [
        { title: "Front-end", description: "Des interfaces claires sur ordinateur comme sur mobile." },
        { title: "Backend", description: "Des API et une logique applicative adaptées à de vrais flux de travail." },
        { title: "Données et plateforme", description: "Des modèles de données, contrôles d’accès et intégrations pratiques." },
        { title: "Mobile et outils", description: "Une livraison multiplateforme appuyée par une chaîne d’outils rigoureuse." },
      ],
    },
    about: {
      kicker: "À propos", title: "J’aime participer à tout le processus de création.",
      first: "Je m’appelle Tri. Récemment diplômé en développement de logiciels, j’aime transformer un problème flou en produit fonctionnel : concevoir l’interface, définir les données, bâtir le flux et tester le résultat.",
      second: "Je recherche une équipe où je pourrai contribuer à de vrais produits, apprendre auprès de développeurs expérimentés et devenir un ingénieur logiciel fiable.",
      contactKicker: "Travaillons ensemble", contactTitle: "Ouvert aux occasions juniors partout au Canada.",
      contactText: "Les postes en front-end, full-stack et développement logiciel me correspondent le mieux.", email: "M’écrire", github: "Profil GitHub", linkedin: "Profil LinkedIn",
    },
    footer: { built: "Créé avec Next.js, TypeScript et beaucoup d’attention.", top: "Retour en haut" },
  },
  vi: {
    languageName: "Tiếng Việt",
    controls: { language: "Chọn ngôn ngữ", light: "Chuyển sang giao diện sáng", dark: "Chuyển sang giao diện tối" },
    nav: { aria: "Điều hướng chính", top: "Tri Do, về đầu trang", work: "Dự án", experience: "Kinh nghiệm", skills: "Kỹ năng", about: "Giới thiệu", resume: "CV" },
    hero: {
      eyebrow: "Junior Full-Stack Developer | React · Next.js · TypeScript",
      title: "Tôi xây dựng sản phẩm đáng tin cậy từ giao diện đến cơ sở dữ liệu.",
      lede: "Mới tốt nghiệp chương trình diploma ngành Phát triển Phần mềm tại NBCC, có kinh nghiệm thực tế với giao diện React và Next.js, ứng dụng di động, API có kiểu dữ liệu, xác thực và quy trình kết nối cơ sở dữ liệu.",
      view: "Xem ShopPilot", download: "CV Full-Stack", frontEndResume: "CV Front-End",
      locationAria: "Địa điểm và khả năng làm việc", location: "Đang sống tại Moncton, Canada", availability: "Sẵn sàng cho vị trí junior trên toàn Canada",
    },
    proof: {
      aria: "Tóm tắt kỹ thuật dự án nổi bật", shipping: "Đang phát triển", active: "Dự án đang hoạt động", flagship: "Dự án chủ lực",
      description: "Quản lý sản phẩm, tồn kho, đơn hàng, lưu trữ và phân tích dành cho cửa hàng.",
      commits: "Git commits", platforms: "Nền tảng", isolation: "Tách biệt dữ liệu", caseStudy: "Xem kiến trúc ứng dụng",
    },
    highlights: { aria: "Điểm nổi bật của portfolio", internship: "Kỳ thực tập chuyên môn", projects: "Dự án được chọn", experience: "Kinh nghiệm sản phẩm đầu-cuối" },
    work: {
      kicker: "Dự án tiêu biểu", title: "Minh chứng quan trọng hơn từ khóa.",
      intro: "Những dự án chọn lọc thể hiện tư duy sản phẩm, chiều sâu triển khai và khả năng hoàn thiện phần mềm thực tế.",
      featured: "Dự án chủ lực", type: "Vận hành cửa hàng đa nền tảng",
      summary: "Bảng điều khiển theo hướng sản phẩm thực tế, giúp quản lý sản phẩm, tồn kho, đơn hàng, cài đặt cửa hàng, hình ảnh và số liệu hiệu suất trong một ứng dụng responsive.",
      live: "Mở app (đăng nhập)", source: "Xem mã nguồn", preview: "Xem giao diện",
      previewTitle: "Ảnh giao diện ShopPilot",
      previewIntro: "Xem các màn hình quản lý cửa hàng bên dưới. Không cần tài khoản.",
      loginNote: "Ứng dụng trực tuyến yêu cầu tài khoản cửa hàng.",
      engineering: [
        "Xác thực Supabase, route được bảo vệ và khôi phục phiên đăng nhập",
        "PostgreSQL Row Level Security bảo vệ dữ liệu và tệp của từng cửa hàng",
        "CRUD sản phẩm, lọc tồn kho, tải ảnh, xử lý đơn hàng và hoàn tiền",
        "Truy cập dữ liệu có kiểu cho doanh thu, tỷ lệ chuyển đổi và phân tích sản phẩm",
      ],
      screenshotsAria: "Ảnh giao diện ShopPilot", viewGithub: "Mở {title}",
    },
    shots: [
      { label: "Tổng quan", alt: "Bảng điều khiển ShopPilot hiển thị doanh thu, đơn hàng, tồn kho và tỷ lệ chuyển đổi", caption: "Màn hình tổng quan tập hợp doanh thu, đơn hàng đang xử lý, cảnh báo tồn kho và hoạt động gần đây." },
      { label: "Sản phẩm", alt: "Màn hình quản lý sản phẩm ShopPilot với tìm kiếm, bộ lọc, giá và tồn kho", caption: "Màn hình sản phẩm hỗ trợ tìm kiếm, lọc tồn kho, quản lý giá và trạng thái hiển thị." },
      { label: "Phân tích", alt: "Màn hình phân tích ShopPilot hiển thị doanh thu tuần và rủi ro tồn kho", caption: "Màn hình phân tích dùng dữ liệu mẫu để minh họa doanh thu, lượt truy cập, chuyển đổi và rủi ro tồn kho." },
    ],
    projects: [
      {"type": "Storefront Next.js", "title": "ShopPilot Storefront", "description": "Phần dành cho khách hàng của ShopPilot: trang cửa hàng, danh mục sản phẩm và giỏ hàng cục bộ dùng chung dữ liệu Supabase với ứng dụng quản lý. MVP hiện tại chưa có bước đặt hàng và thanh toán.", "signals": ["Component React tái sử dụng", "Duyệt sản phẩm và giỏ hàng", "Sự kiện phân tích storefront"]},
      { type: "Nền tảng đặt lịch full-stack", title: "ScheduleBooker", description: "Nền tảng đặt lịch Flask đa ngôn ngữ cho khách và người dùng có tài khoản, với kiểm tra lịch trùng, lịch và báo cáo quản trị, hủy lịch có audit và PostgreSQL khi triển khai production.", signals: ["Luồng đặt lịch responsive", "PostgreSQL + migrations", "Bảo mật và kiểm thử tự động"] },
      { type: "Ứng dụng web full-stack", title: "Restaurant Event Management", description: "Hệ thống sự kiện kết nối cơ sở dữ liệu với giao diện render từ server, biểu mẫu có xác thực, tìm kiếm theo tên/ngày và cơ chế lưu trữ thay vì xóa hẳn.", signals: ["Kiến trúc MVC", "Xác thực phía server", "Quy trình tìm kiếm và lưu trữ"] },
      { type: "Backend REST API", title: "License Plate Assignment API", description: "REST API xác thực VIN và quản lý việc cấp, kiểm tra, thu hồi biển số theo định dạng Ontario với dữ liệu được lưu bền vững.", signals: ["Middleware API key", "Xác thực và xử lý lỗi", "Quy trình request có tài liệu"] },
    ],
    career: {
      kicker: "Kinh nghiệm và học vấn", title: "Xây dựng từ trải nghiệm thực tế.", experience: "Kinh nghiệm", education: "Học vấn",
      internTitle: "Thực tập sinh Phát triển Phần mềm", internPoints: [
        "Triển khai tính năng đánh giá, kiểm thử hoạt động và sửa lỗi dựa trên góp ý của người hướng dẫn.",
        "Phát triển và kiểm thử quy trình CRUD, kiểm tra dữ liệu đầu vào và logic ứng dụng kết nối cơ sở dữ liệu.",
        "Sử dụng Git để quản lý thay đổi trong nhóm phát triển và ghi lại tiến độ cho người hướng dẫn.",
      ],
      diploma: "Công nghệ Thông tin: Phát triển Phần mềm",
      college: "New Brunswick Community College · Moncton",
      educationText: "Chương trình đào tạo phát triển web full-stack, cơ sở dữ liệu, API, ứng dụng di động, kiểm thử và quy trình phát triển phần mềm theo nhóm.",
    },
    skills: {
      kicker: "Năng lực", title: "Công nghệ gắn liền với kết quả.",
      intro: "Công nghệ có thể đa dạng, nhưng trọng tâm luôn nhất quán: giao diện rõ ràng, logic ứng dụng đáng tin cậy và luồng dữ liệu dễ bảo trì.",
      groups: [
        { title: "Front end", description: "Giao diện rõ ràng trên cả máy tính và thiết bị di động." },
        { title: "Back end", description: "API và logic ứng dụng phục vụ những quy trình thực tế." },
        { title: "Dữ liệu và nền tảng", description: "Mô hình dữ liệu, kiểm soát truy cập và tích hợp thiết thực." },
        { title: "Di động và quy trình", description: "Phát triển đa nền tảng với bộ công cụ có tổ chức." },
      ],
    },
    about: {
      kicker: "Giới thiệu", title: "Tôi thích toàn bộ quá trình xây dựng sản phẩm.",
      first: "Tôi là Tri, một tân cử nhân Phát triển Phần mềm. Tôi thích biến một vấn đề chưa rõ ràng thành sản phẩm hoạt động được: thiết kế giao diện, xác định dữ liệu, xây dựng quy trình và kiểm thử kết quả.",
      second: "Tôi đang tìm một đội ngũ phù hợp với junior, nơi tôi có thể đóng góp vào sản phẩm thực tế, học hỏi từ các lập trình viên giàu kinh nghiệm và phát triển thành một kỹ sư phần mềm đáng tin cậy.",
      contactKicker: "Cùng làm việc nhé", contactTitle: "Sẵn sàng cho cơ hội junior trên toàn Canada.",
      contactText: "Các vị trí front-end, full-stack và phát triển phần mềm là phù hợp nhất.", email: "Gửi email", github: "Trang GitHub", linkedin: "Trang LinkedIn",
    },
    footer: { built: "Xây dựng bằng Next.js, TypeScript và sự chỉn chu.", top: "Về đầu trang" },
  },
} as const;

export type Language = keyof typeof translations;
